# ------------ 基本站点信息 ------------
baseURL = "https://jinzstudio.com/"   # ← 改成你的正式域名；本地测试不影响
title = "JinzStudio"
languageCode = "zh-cn"
theme = "PaperMod"
defaultContentLanguage = "zh"
enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "G-M8MMBKRXQZ"

[pagination]
  pagerSize = 12

# 输出（含 JSON，给搜索用）
[outputs]
  home    = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy= ["HTML", "RSS"]
  term    = ["HTML", "RSS"]
  page    = ["HTML"]

# 文章链接
[permalinks]
  posts = "/posts/:year/:month/:slug/"

[taxonomies]
  category = "categories"
  tag      = "tags"
  series   = "series"

[markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true
  [markup.highlight]
    noClasses = false
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  defaultTheme = "auto"
  disableThemeToggle = false
  description = "JinzStudio的独立开发笔记。"
  keywords = ["Godot", "MiniGame", "游戏开发", "WebGame", "个人博客", "JinzStudio"]
  ShowReadingTime = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowShareButtons = false
  ShareButtons = ["twitter","bilibili"]  # 指定要显示的平台
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = true
  ShowPostDate = true
  mainSections = ["posts"]
  TocOpen = false

  [params.homeInfoParams]
    Title = "Hello，这里是 JinzStudio"
    Content = "记录 Godot 游戏开发、算法与独立开发流水账。这里是我的知识与项目基地。"

  [[params.socialIcons]]
    name = "bilibili"
    url  = "https://space.bilibili.com/73006616" # ← 改成你的
  [[params.socialIcons]]
    name = "email"
    url  = "mailto:jinzstudio10@gmail.com"            # ← 改成你的

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    includeMatches = false
    includeScore = false
    minMatchCharLength = 2
    location = 0
    distance = 1000
    threshold = 0.4
    limit = 10 # 限制返回结果条数（Fuse.js 方法参数也支持limit）
    keys = ["title", "permalink", "summary", "content"]
  
  [params.assets]
    favicon = "favicon.ico"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    apple_touch_icon = "apple-touch-icon.png"
    safari_pinned_tab = "favicon.ico" # 如果没有专门的 svg，可以先用 ico
    customCSS = ["css/extended/custom.css"]
    css = ["css/extended/showcase.css"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "POSTS"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "ABOUT"
    url = "/about/"
    weight = 40
  
  [[menu.main]]
    identifier = "games"
    name = "GAME"
    url = "/games/"
    weight = 15
  
  [[menu.main]]
    identifier = "search"
    name = "SEARCH"
    url = "/search/"
    weight = 30

  [[menu.main]]
  identifier = "showcase"
  name = "GODOT"
  url = "/showcase/"
  weight = 20